services:
  server:
    build: .
    volumes:
      - .:/code
      - ./db:/db
    ports:
      - "${APP_PORT}:8001"
    environment:
      APP_SQLITE_DB: /db/db.sqlite
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID:?error}
      COGNITO_USER_CLIENT_ID: ${COGNITO_USER_CLIENT_ID:?error}
      # FIXME: Add a default value later
      COGNITO_ISSUER: ${COGNITO_ISSUER:?error}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-stub}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-stub}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      S3_BUCKET: ${S3_BUCKET:-snwg-rgt-dev-files}
      S3_CUSTOM_ENDPOINT: ${S3_CUSTOM_ENDPOINT:?error}

    command: sh -c 'pnpm install && pnpm tsoa:generate && pnpm dev'
