name: CI

on:
  pull_request:
  push:
    branches:
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-unused:
    name: Identify unused files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Generate spec and routes
        run: pnpm tsoa:generate

      - name: Identify unused files
        run: pnpm lint:unused

  lint-js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Generate spec and routes
        run: pnpm tsoa:generate

      - name: Lint JS
        run: pnpm lint:js

  lint-ts:
    name: Lint TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Generate spec and routes
        run: pnpm tsoa:generate

      - name: Lint JS
        run: pnpm lint:ts
